---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flaskapp_mysqldb
spec:
  serviceName: flaskapp_mysqldb
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp_mysqldb
  template:
    metadata:
      labels:
        app: flaskapp_mysqldb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: flaskapp_mysqldb
        image: 654717204467.dkr.ecr.us-west-2.amazonaws.com/flaskapp_mysqldb:1.0.0
        ports:
        - name: tcp
          protocol: TCP
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 1Gi